event_site/event_site/urls.py
from django.contrib import admin
from django.urls import path, include
from social_django.urls import urlpatterns as social_django_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('events.urls')),
    path('auth/', include((social_django_urls, 'events'), namespace='social')),
]

event_site/events/urls.py
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('accueil', views.accueil, name='accueil'), #changed

    path('', views.index, name='index'),
    path('form', views.get_name),
    path('thanks', views.thanks),
    path('profils', views.profils_view, name='profils_list'),

    path('asso', views.AssosView, name='asso'),
    path('create_asso', views.create_asso),
    path('asso_del/<str:asso_name>', views.del_asso),
    path('asso/<name>', views.AssoDetail, name='asso_detail'),

    path('events', views.EventsView, name='events'),
    path('form_event', views.get_event),

    path('profils/<str:name_>', views.profil_detail, name='profil_detail'),
    path('logged/', views.logged, name='logged'),
    path('passphrase/', views.passphrase, name='passphrase'),
    path('signature/', views.signature_missing),

    path('autocomp/', views.autoCompletion),
    path('member_add/<str:asso_name>', views.AddMember),
    path('member_del/<str:asso_name>', views.DelMember),

    path('pdf/<str:event_name>', views.show_pdf_updated),
    path('list_pdf/', views.list_pdf),
    path('show_pdf/<str:pdf_name>', views.show_pdf),

    path('mail/', views.emails),

    path('sign/<str:event_name>', views.sign),
    path('reject/<str:event_name>', views.reject),
    path('premium/<str:event_name>', views.premium),
    path('add_asso_event/<str:event_name>', views.AddAssoEvent),

    path('stats/', views.get_stats),

    path('logout/', views.logout, name='logout')
]

urlpatterns += staticfiles_urlpatterns()

event_site/events/models.py
from django.db import models
from datetime import datetime
from django.utils import timezone

# Create your models here.

class Person(models.Model):
    name = models.CharField(max_length=255)
    inscription_date = models.DateTimeField('inscription date')
    administration = models.BooleanField(default=False)
    telephone = models.CharField(max_length=255)
    email = models.CharField(max_length=255, default="")
    passphrase = models.BooleanField(default=False)
    image = models.ImageField(upload_to='events/static/images/', null=True)

    def __str__(self):
        return self.name

    def getPath(self):
        l = self.image.path.split('/')
        index = len(l) - 2
        return "/".join(l[index:])

class Association(models.Model):
    name = models.CharField(max_length=255)
    creation_date = models.DateTimeField(auto_now=True)
    description = models.TextField(default="")
    image = models.ImageField(upload_to='static/uploaded-files/')

    def __str__(self):
        return self.name

    def getPath(self):
        l = self.image.path.split('/')
        index = len(l) - 2
        return "/".join(l[index:])

class Bureau(models.Model):
    association_id = models.ForeignKey(Association, on_delete=models.CASCADE, related_name='bureau')
    person_id = models.ForeignKey(Person, on_delete=models.CASCADE)
    role = models.CharField(max_length=255)

    def __str__(self):
        return self.role + " of association " + str(self.association_id)

class Member(models.Model):
    association_id = models.ForeignKey(Association, on_delete=models.CASCADE, related_name='members')
    person_id = models.ForeignKey(Person, on_delete=models.CASCADE, related_name='memb')

    def __str__(self):
        return "member of " + str(self.association_id)

class Administration(models.Model):
    person_id = models.ForeignKey(Person, on_delete=models.CASCADE, related_name='adm')
    role = models.CharField(max_length=255)

    def __str__(self):
        return "adm : " + self.role

class Event(models.Model):
    association_id = models.ForeignKey(Association, on_delete=models.CASCADE, related_name='events')
    creator_id = models.ForeignKey(Person, on_delete=models.CASCADE, related_name='event')
    name = models.CharField(max_length=255)
    date = models.DateField(default=timezone.now())
    hour_begin = models.TimeField(default=datetime.strptime('00:00', '%H:%M').time())
    hour_end = models.TimeField(default=datetime.strptime('23:59', '%H:%M').time())
    recurrence = models.BooleanField(default=False)
    frequence = models.IntegerField(blank=True, null=True)
    frequence_end = models.DateField(blank=True, null=True)
    respo_id = models.ForeignKey(Person, on_delete=models.DO_NOTHING, related_name='respo_event')
    respo_class = models.CharField(max_length=255)
    tutor_id = models.ForeignKey(Administration, on_delete=models.DO_NOTHING, related_name='tutor_event', null=True)
    nb_externs = models.IntegerField()
    nb_students = models.IntegerField()
    nb_members = models.IntegerField()
    description = models.CharField(max_length=1000)
    insurance = models.BooleanField(default=False)
    material = models.CharField(max_length=1000, blank=True)
    alcoholic_drinks = models.BooleanField(default=False)
    soft_drinks = models.BooleanField(default=False)
    comments = models.CharField(max_length=1000, blank=True)
    respo_sign = models.BooleanField(default=False)
    president_sign = models.BooleanField(default=False)
    tutor_sign = models.BooleanField(default=False)
    respo_asso_sign = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    def get_day(self):
        return self.date.day

    def get_month(self):
        if self.date.month == 1:
            return 'JANV'
        elif self.date.month == 2:
            return 'FEVR'
        elif self.date.month == 3:
            return 'MARS'
        elif self.date.month == 4:
            return 'AVR'
        elif self.date.month == 5:
            return 'MAI'
        elif self.date.month == 6:
            return 'JUIN'
        elif self.date.month == 7:
            return 'JUIL'
        elif self.date.month == 8:
            return 'AOUT'
        elif self.date.month == 9:
            return 'SEPT'
        elif self.date.month == 10:
            return 'OCT'
        elif self.date.month == 11:
            return 'NOV'
        else:
            return 'DEC'

    def get_begin_hour(self):
        return self.hour_begin.strftime("%H:%M")
    def get_end_hour(self):
        return self.hour_end.strftime("%H:%M")

class PossibleRoom(models.Model):
    name = models.CharField(max_length=100)
    KB_VJ = models.BooleanField(default=False) # KB = false, VJ = true

    def __str__(self):
        return self.name

class ReservedRoom(models.Model):
    event_id = models.ForeignKey(Event, on_delete=models.CASCADE, related_name='rooms')
    room_id = models.ForeignKey(PossibleRoom, on_delete=models.CASCADE, related_name='reservations')

    def __str__(self):
        return "room " + str(self.room_id) + " reserved by " + str(self.event_id)

class Brouillon(models.Model):
    association = models.CharField(max_length=1000)
    creator_id = models.ForeignKey(Person, on_delete=models.CASCADE, related_name='brouillon')
    creation_date = models.DateTimeField('creation date', null=True)
    name = models.CharField(max_length=1000)
    date = models.CharField(max_length=1000)
    hour_begin = models.CharField(max_length=1000)
    hour_end = models.CharField(max_length=1000)
    recurrence = models.BooleanField(default=False)
    frequence = models.CharField(max_length=1000, null=True)
    frequence_end = models.CharField(max_length=1000, null=True)
    respo_id = models.CharField(max_length=1000, null=True)
    respo_class = models.CharField(max_length=1000)
    tutor_id = models.CharField(max_length=1000)
    nb_externs = models.CharField(max_length=1000)
    nb_students = models.CharField(max_length=1000)
    nb_members = models.CharField(max_length=1000)
    description = models.CharField(max_length=1000)
    insurance = models.BooleanField(default=False)
    material = models.CharField(max_length=1000)
    alcoholic_drinks = models.BooleanField(default=False)
    soft_drinks = models.BooleanField(default=False)
    comments = models.CharField(max_length=1000)
    rooms_VJ = models.CharField(max_length=1000, null=True)
    rooms_KB = models.CharField(max_length=1000, null=True)

class AssoSupEvent(models.Model):
    event_id = models.ForeignKey(Event, on_delete=models.CASCADE, related_name='asso_sup')
    association_id = models.ForeignKey(Association, on_delete=models.CASCADE, related_name='events_sup')

    def __str__(self):
        return "asso " + self.association_id.name + " est ajoute a l'event " + self.event_id.name

event_site/events/forms.py
from django import forms
from . import models


class NameForm(forms.Form):
    your_name = forms.CharField(label='Your name', max_length=100)


class PersonForm(forms.ModelForm):
    class Meta:
        model = models.Person
        image = forms.ImageField()
        fields = []


class PassphraseForm(forms.Form):
    passphrase = forms.CharField(label='passphrase', max_length=512)


class EventForm(forms.ModelForm):
    association = forms.CharField(max_length=255, required=False,
        widget = forms.TextInput(attrs = {
            'id': 'asso',
            'class': 'search',
            'autocomplete': 'off',
        })
    )
    respo_name = forms.CharField(max_length=255, required=False,
        widget = forms.TextInput(attrs = {
            'id': 'respo',
            'class': 'search',
            'autocomplete': 'off',
        })
    )
    tutor_name = forms.CharField(max_length=255, required=False,
        widget = forms.TextInput(attrs = {
            'id': 'tutor',
            'class': 'search',
            'autocomplete': 'off',
        })
    )
    #rooms = forms.CharField(max_length=511)
    #site = forms.CharField(max_length=100)

    class Meta:
        model = models.Event
        fields = [
            'name',
            'date',
            'hour_begin',
            'hour_end',
            'recurrence',
            'frequence',
            'frequence_end',
            'respo_class',
            'nb_students',
            'nb_members',
            'nb_externs',
            'description',
            'insurance',
            'material',
            'alcoholic_drinks',
            'soft_drinks',
            'comments'
        ]
        widgets = {'respo_id': forms.TextInput}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.Meta.fields:
            self.fields[field].required = False

class AssoCreateForm(forms.ModelForm):
    president = forms.CharField(max_length=255,
        widget = forms.TextInput(attrs = {
            'id': 'pres',
            'class': 'search',
            'autocomplete': 'off',
        })
    )
    tresorier = forms.CharField(max_length=255,
        widget = forms.TextInput(attrs = {
            'id': 'tres',
            'class': 'search',
            'autocomplete': 'off',
        })
    )
    secretaire = forms.CharField(max_length=255,
        widget = forms.TextInput(attrs = {
            'id': 'secr',
            'class': 'search',
            'autocomplete': 'off',
        })
    )
    description = forms.CharField(widget=forms.Textarea)
    class Meta:
        model = models.Association
        image = forms.ImageField()
        fields = ['name']

class AssoAddMemberForm(forms.ModelForm):
    member = forms.CharField(max_length=255)
    class Meta:
        model = models.Member
        fields = []

class AssoDelMemberForm(forms.ModelForm):
    member = forms.CharField(max_length=255)
    class Meta:
        model = models.Member
        fields = []

class EventAddAssoForm(forms.ModelForm):
    class Meta:
        model = models.AssoSupEvent
        fields = []

event_site/events/templates/connection/logged.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Epita Connect Example - Logged</title>
</head>
<body>
    <h1>Hello {{ user.first_name }}</h1>
    <p>Username: {{ user.username }}</p>
    <p>Promo: {{ extra_data.promo }}</p>
    <p><a href="{% url "logout" %}">Logout</a></p>
</body>
</html>

event_site/events/templates/connection/passphrase.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<meta name="author" content="">
		<title>Première connexion</title>


		<!--Bootstrap link to make it work-->
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

		<link rel="stylesheet" type="text/css" href="{% static 'asso.css' %}">

		{% include 'try_menu.html' with is_admin=is_administration %}
	</head>

	<body>
		<div class="container col-sm-8 text-white text-center">
            
            <hr>
            <div class="shadow-lg p-3 mb-5 rounded" style="background-color: transparent;">
            	<h1>Première connexion</h1>
 			</div>	

			<div class="card" style="background-color: transparent;">
			  <div class="card-header">
			    
			  </div>
			  <div class="card-body">
			    <h5 class="card-title">Bonjour {{ user.first_name }}. </h5>
			    <p class="card-text">Afin de pouvoir commencer à utiliser ce site, veuillez renseigner une passphrase, elle vous sera redemandé à chaque fois que vous voudrez signer.</p>


            <div class="text-light">
		    	<form action="/passphrase/" method="POST" enctype="multipart/form-data" style='padding-top:15px;'>
		        {% csrf_token %}
		        <!--{{ form }}-->
					{{ form.non_field_errors }}
					<div class="fieldWrapper">
						{{ form.passphrase.errors }}
						<label for="{{ form.passphrase.id_for_label }}">Passphrase :</label>
						{{ form.passphrase }}
					</div>
		        	<br/>
		        	<input type="submit" value="Submit">
		    	</form>
			</div>
			</div>
        </div>

	</body>

event_site/events/templates/connection/signature.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<meta name="author" content="">
		<title>Téléchargement Signature</title>


		<!--Bootstrap link to make it work-->
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

		<link rel="stylesheet" type="text/css" href="{% static 'asso.css' %}">

		{% include 'try_menu.html' with is_admin=is_administration %}
	</head>

	<body>
		<div class="container col-sm-8 text-white text-center">

            <hr>
            <div class="shadow-lg p-3 mb-5 rounded" style="background-color: transparent;">
            	<h1>Première connexion</h1>
 			</div>

			<div class="card" style="background-color: transparent;">
			  <div class="card-header">

			  </div>
			  <div class="card-body">
			    <h5 class="card-title">Bonjour {{ user.first_name }}. </h5>
			    <p class="card-text">Merci de bien vouloir importer votre paraphe.</p>


            <div class="text-light">
		    	<form action="/signature/" method="POST" enctype="multipart/form-data" style='padding-top:15px;'>
		        {% csrf_token %}
		        <!--{{ form }}-->
		        	{{ form.non_field_errors }}
		        	<div class="fieldWrapper">
		            	{{ form.logo.errors }}
		            	<label for="{{ form.logo.id_for_label }}">Signature:</label>
		            	{{ form.logo }}
		            	<p>
		                	<input id="id_image" type="file" class="" name="image">
		            	</p>
                  <p id="demo"></p>
                  <pre id="file-content" style="color:white;"></pre>
		        	</div>
		        	<br/>
		        	<input type="submit" value="Submit">

		    	</form>
			</div>
			</div>
        </div>
	</body>

<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>

<script>
var key = "";

function readSingleFile(e) {
    var file = e.target.files[0];
    if (!file) {
        return;
    }
    var reader = new FileReader();
    reader.onload = function(e) {
        var contents = e.target.result;
        var res = encrypt(contents);
        res.then(r => {
            //alert("res end = " + r);
            //alert("key end = " + key);
        });
    };
    reader.readAsText(file);
}

function displayContents(contents) {
    var element = document.getElementById("file-content");
    element.textContent = contents;
}

document.getElementById('id_image').addEventListener('change', readSingleFile, false);


function encrypt(content) {
    var encoder = new TextEncoder('utf-8');
    var dataArrayBufferView = encoder.encode(content);

    var result = new ArrayBuffer();

    var aesAlgorithmKeyGen = {
        name: "AES-GCM",
        length: 128,
    };

    var aesAlgorithmEncrypt = {
        name: "AES-GCM",
        iv: window.crypto.getRandomValues(new Uint8Array(16))
    };

    return window.crypto.subtle.generateKey(aesAlgorithmKeyGen, true, ["encrypt", "decrypt"])
    .then ((aesKey) => {
            key = String(aesKey);
            return window.crypto.subtle.encrypt(aesAlgorithmEncrypt, aesKey, dataArrayBufferView);
        }
    ).then(ciphertext => {
            return ciphertext;
        }
    );
}
</script>